[versions]
    minecraft = '26.3-snapshot-10'
    fabric-loader = "0.19.5"

    fabric = "0.158.3+26.3"

    terraformwoodapi = '17.0.1'

[libraries]
    minecraft = { module = 'com.mojang:minecraft', version.ref = 'minecraft' }

    fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
    fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }

    terraformwoodapi = { module = 'com.terraformersmc.terraform-api:terraform-wood-api-v1', version.ref = 'terraformwoodapi' }
